### ISSUE TITLE
Hands on Kubernetes cluster created in issue #1

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#4]
Execute these on the k8s cluster created in https://github.com/vasavi-27/Tasks/issues/1

1. Create a secret with a username and password as data. Create a pod with this secret as a volume mount and display the mounted secret by SSHing into Pod.
2. Copy a file from local host to pod and vice-versa(Copy a file from pod to local host)
3. Deploy Nginx application on the k8s cluster and expose it via a NodePort service.

Estimated Time: 2 days

**Comment by vasavi-27** [comment]
Started on 27th Dec

**Comment by vasavi-27** [comment]
**Task-1:**
`secret-pod.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
```
`secret.yaml`:
```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
```
1.`kubectl apply -f https://k8s.io/examples/pods/inject/secret.yaml`
2.`kubectl apply -f https://k8s.io/examples/pods/inject/secret-pod.yaml`
3.`kubectl get pod secret-test-pod`
4.`kubectl exec -it secret-test-pod -- /bin/bash`
     `ls /etc/secret-volume`
5.`echo "$( cat /etc/secret-volume/username )"`
     `echo "$( cat /etc/secret-volume/password )"`

**Comment by vasavi-27** [comment]
**Task-2**

1.`kubectl cp <pod_name>:<file_path> <destination_path>`
2.`kubectl cp <local_source_path> <pod_name>:<destination_path>`

**Comment by vasavi-27** [comment]
**Task-3**


1. `kubectl create deployment nginx --image=nginx`
2. `kubectl get deployments`
3. `kubectl describe deployment nginx`
4. `kubectl create service nodeport nginx --tcp=80:80`
5. `curl (public-node-ip):(node-port)`
                            
                                                   OR

`nginx-deployment.yaml`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  labels:
    app: nginx-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx
          image: nginx
      terminationGracePeriodSeconds: 5
      serviceAccountName: default
```
`nginx-service.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-hello-world
  name: nginx-hello-world
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 31704
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-hello-world
  type: NodePort
```

1. `kubectl apply -f nginx-deployment.yaml`
2. `kubectl apply -f nginx-service.yaml`
3. `curl (public-node-ip):(node-port)`
