### ISSUE TITLE
Create an Ingress in k8s cluster

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#5]
This task is to create an Ingress resource in your single-node Kubernetes cluster.
1. Create two deployments with pods displaying different text in each of them
2. Create two ClusterIP services that point to the above two deployments.
3. Create an ingress resource that defines rules with different path values for each of the above services.

Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
Also, refer the video from Swapnil in Kubernetes selfy shot training (Specifically go through ingress section)

**Comment by vasavi-27** [comment]
**Task-3:**
`ingress.yaml`:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /orange
        pathType: Prefix
        backend:
          service:
            name: orange-service
            port:
              number: 5678
      - path: /mango
        pathType: Prefix
        backend:
          service:
            name: mango-service
            port:
              number: 5678
      - path: /banana
        pathType: Prefix
        backend:
          service:
            name: banala-service
            port:
              number: 5678
```
`banana.yaml`
```kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"
     

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
   ```
`mango.yaml:`
```
kind: Pod
apiVersion: v1
metadata:
  name: mango-app
  labels:
    app: mango
spec:
  containers:
    - name: mango-app
      image: hashicorp/http-echo
      args:
        - "-text=mango"
     

---

kind: Service
apiVersion: v1
metadata:
  name: mango-service
spec:
  selector:
    app: mango
  ports:
    - port: 5678 # Default port for image
```
`orange.yaml:`
```
kind: Pod
apiVersion: v1
metadata:
  name: orange-app
  labels:
    app: orange
spec:
  containers:
    - name: orange-app
      image: hashicorp/http-echo
      args:
        - "-text=orange"
      

---

kind: Service
apiVersion: v1
metadata:
  name: orange-service
spec:
  selector:
    app: orange
  ports:
    - port: 5678 # Default port for image
```

1. `kubectl apply -f ingress.yaml`
2. `kubectl apply -f mango.yaml`
3. `kubectl apply -f orange.yaml`
4. `kubectl apply -f banana.yaml`
5. `curl (public-node-ip):(node-port)`
