### ISSUE TITLE
Create a cronjob on k8s cluster

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#8]
Create a Cron job that runs every hour at 10th minute.
Use busybox image for its container.

**Comment by vasavi-27** [comment]
**cronjob.yaml**
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "10* * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
